ceph/calamari

tests/calamari_ctl.py
tests/ceph_ctl.py
tests/test_ceph_ctl.py
tests/test_monitoring.py
tests/test_pool_management.py

Same changes as in wip-testing merge to master (e0b9b21a31dd8387b8c240110f6c376729cc08fc), on the 1.2.2 branch, for convenience

wip-testing-1.2.2

---

salt/local/postgres.sls
salt/local/services.sls
salt/srv/salt/diamond.sls

Signed-off-by: Dan Mick <dan.mick@redhat.com>

salt/local: test for RHEL 7.x rather than RHEL 7.0

---

Makefile

Silence foul flake8

---

doc/development/dev_env.rst

updating dev env Vagrant run instuctions to provide link on running server with supervisord, since otherwise this can be found only on the youtube video
Also fixed a minor typo s/build/built
Signed-Off-By: Abhishek Lekshmanan <abhishek.lekshmanan@ril.com>

doc: update dev env vagrant instructions

---

cthulhu/cthulhu/manager/crush_node_request_factory.py
cthulhu/tests/test_crush_node_request_factory.py
doc/operations/configuring_ceph.rst
doc/operations/index.rst
salt/srv/salt/base/calamari-crush-location.py
salt/srv/salt/osd_crush_location.sls
salt/srv/salt/top.sls
tests/ceph_ctl.py
tests/test_crush.py

Wip crush tracking

---

doc/index.rst

doc: add helpful information about calamari to index

---

debian/control

packaging: fix typo in debian/control

---

doc/development/dev_env.rst
vagrant/devmode/Vagrantfile
vps_bootstrap.sh

Updated docs to reflect the new process
Signed-off-by: Gregory Meno <gregory.meno@inktank.com>
@dmick

devmode: pin to a specific version of salt

---

salt/srv/salt/_modules/smart.py
salt/srv/salt/smart.sls
salt/srv/salt/top.sls

@dmick 
Adds a module to wrap the mess that is smartctl, reports only reallocated_sectors

Wip add smart

---

salt/srv/salt/_modules/ceph.py

ceph-module: backport admin socket pattern matching

---

salt/srv/salt/diamond.sls

diamond: fix systemd service restart

---

salt/local/postgres.sls
salt/local/services.sls
salt/srv/salt/diamond.sls
tests/calamari_ctl.py
tests/ceph_ctl.py

This isn't any cleaner than your attempt, Gregory, so I give up; the destination is what matters, after all.  The upside is that this one is passing tests.

Pull all the 1.2.3 changes into 1.3

---

cthulhu/cthulhu/calamari_ctl.py

calamari: add path to update minions during upgrade

---

doc/development/building_packages.rst

Signed-off-by: Dan Mick <dan.mick@inktank.com>

doc: Clarifying that builds generally don't run highstate automatically

---

vagrant/centos-build/salt/roots/build_deps.sls

centos: add httpd build dep.

---

salt/srv/salt/base/calamari-crush-location.py

Fixes #11559
@dmick @jcsp 
http://tracker.ceph.com/issues/11559

calamari: fix getting previous CRUSH location

---

salt/local/postgres.sls
salt/local/services.sls
salt/srv/salt/_modules/ceph.py
salt/srv/salt/base/calamari-crush-location.py
salt/srv/salt/diamond.sls
tests/calamari_ctl.py
tests/ceph_ctl.py

@dmick Stuff in 1.3 that is not in master but should be.

Master 1.3 merge

---

doc/development/building_packages.rst
salt/srv/salt/base/calamari-crush-location.py

@dmick this merged in to 1.3 in #297 and needs to go to master now

promoting merges form 1.3 to master

---

vagrant/centos-build/salt/roots/make_packages.sls
vagrant/centos-build/salt/roots/setvars
vagrant/precise-build/salt/roots/make_packages.sls
vagrant/precise-build/salt/roots/setvars
vagrant/rhel-build/salt/roots/make_packages.sls
vagrant/rhel-build/salt/roots/setvars
vagrant/rhel7-build/salt/roots/make_packages.sls
vagrant/rhel7-build/salt/roots/setvars
vagrant/trusty-build/salt/roots/make_packages.sls
vagrant/trusty-build/salt/roots/setvars
vagrant/wheezy-build/salt/roots/make_packages.sls
vagrant/wheezy-build/salt/roots/setvars

Signed-off-by: Dan Mick <dan.mick@redhat.com>

For non-vagrant builds, make $WORKSPACE/pkgs as a package delivery point

---

vagrant/centos-build/salt/roots/build_deps.sls
vagrant/rhel-build/salt/roots/build_deps.sls
vagrant/rhel7-build/salt/roots/build_deps.sls

Signed-off-by: Dan Mick <dan.mick@redhat.com>
Conflicts:
vagrant/centos-build/salt/roots/build_deps.sls

Add new build dependencies

---

requirements/2.7/requirements.txt
vps_bootstrap.sh

Update 2.7 requirements file and vps_bootstrap.sh to point to 2015.5.1 salt version.

requirements.txt and vps_bootstrap: Update salt version to 2015.5.1

---

README.rst
doc/operations/minion_connect.rst
doc/operations/server_install.rst

docs: add link to packages

---

minion-sim/minion_sim/child.py

Signed-Off-By: Joe Handzik <joseph.t.handzik@hp.com>

minion-sim: Fix minion attribute error

---

.travis.yml
calamari-common/calamari_common/salt_wrapper.py

@dmick 
I've run tests, built docs and travis-cI liked it.
I've now re-based it to 1.2.3.
Let me know what you think

Wip salt wrapper

---

.travis.yml
calamari-common/calamari_common/salt_wrapper.py

git checkout 1.3
git reset --hard origin/1.3
git status
git merge --no-ff origin/1.2.3
git checkout -b wip-mergeup
git push origin wip-mergeup

Wip mergeup

---

calamari-common/calamari_common/types.py
cthulhu/tests/interesting_osd_map.json
cthulhu/tests/osd_map-7883.json
minion-sim/minion_sim/ceph_cluster.py
rest-api/calamari_rest/serializers/v2.py
rest-api/calamari_rest/views/v2.py
salt/srv/salt/_modules/ceph.py

Hey guys,
Here's my set of changes to propagate the device node stuff I added. Tested a bunch over the last day with minion-sim, so I'm pretty confident in everything outside of the ceph.py salt code. Feedback across the board would be appreciated. For reference, here's my Ceph commit that goes with all this: https://github.com/ceph/ceph/commit/4fe62cd7a1761c73ab526978a0a6a3cab4f8e2c4
It's amazing what you can get done when you use Salt 2014. :P

osd metadata additions

---

cthulhu/cthulhu/manager/request_collection.py

@dmick @
I wasn't able to capture this condition in the integration-tests
pass is obviously the wrong thing here
Fixes: #13008

cthulhu: process UserRequest on_map response from many clusters

---

salt/srv/salt/base/calamari-crush-location.py

calamari-crush-location.py has a '--cluster' parameter but never makes
use of it. This change adds customized ceph cluster name support for
this script so that it doesn't always assume ceph cluster name to be
'ceph'.
This change also wraps long line code to less than 80 characters.

Add ceph cluster name support for calamari-crush-location

---

vagrant/centos6-build/Vagrantfile
vagrant/precise-build/Vagrantfile
vagrant/trusty-build/Vagrantfile
vagrant/wheezy-build/Vagrantfile

@dmick @ktdreyer 
I source more authentic base-boxes and deal with the saga of broken salt-bootstrap

Wip fix packaging

---

repobuild/conf/precise/upstream.packages
repobuild/conf/trusty/upstream.packages
repobuild/conf/wheezy/upstream.packages

fix python-msgpack package name.

fix python-msgpack package name

---

calamari-common/calamari_common/types.py

Fixes: BZ1303241
it seems that cthulhu is crashing when it's been upgraded to look for
osd_metadata but the ceph.py module that includes it in OSDMap has not
yet been distributed to the agent running on the cluster

calamari-common: accept OSDMaps that do not contain osd_metadata

---

cthulhu/cthulhu/manager/eventer.py

This patch adds osd_uuid info along with other details
emitted to salt bus during osd related events.
Signed-off-by: Darshan N <dnarayan@redhat.com>

Cthulhu: Get OSD uuid along with events related to osd.

---

cthulhu/cthulhu/manager/pool_request_factory.py
rest-api/calamari_rest/serializers/v2.py

rest-api: allow pool creation to omit erasure coding fields

---

calamari-common/calamari_common/remote/mon_remote.py

The problem here is that we were leaking
file descriptors. This wasn't a problem when we
used salt-minion to invoke code using librados
because those processes were short lived.
Now that mon_remote handles the function that we
used to rely on ceph.py for and mon_remote is part
of calamari-lite -- a long running process -- we
need to be better about cleaning up.

calamari-common: add a context manager to clean up Rados connections

---

calamari-common/calamari_common/remote/mon_remote.py

mon_remote: make it more robust when cluster is being built

---

rest-api/calamari_rest/serializers/v2.py
rest-api/calamari_rest/views/v2.py

rest-api: add mountpoint info for osd data and journal

---

calamari-common/calamari_common/remote/mon_remote.py
calamari-common/calamari_common/types.py
rest-api/calamari_rest/serializers/v2.py
rest-api/calamari_rest/views/v2.py

rest-api: adds leader field to mon endpoint

---

vps_bootstrap.sh

update apt first then install latest salt

---

.travis.yml

chown pip cache back to travis

---

calamari-common/calamari_common/remote/__init__.py
calamari-common/calamari_common/remote/mon_remote.py
calamari-web/calamari_web/settings.py
calamari.spec
cthulhu/cthulhu/calamari_ctl.py
debian/control
requirements/lite.txt
rest-api/calamari_rest/views/database_view_set.py
rest-api/calamari_rest/views/rpc_view.py
rest-api/calamari_rest/views/v1.py
rest-api/tests/rest_api_unit_test.py
rest-api/tests/test_auth.py
rest-api/tests/test_crush_node_ancestry.py
rest-api/tests/test_crushmap.py
rest-api/tests/test_keys.py
rest-api/tests/test_mon.py
rest-api/tests/test_osd.py
rest-api/tests/test_pool.py
rest-api/tests/test_saltkey.py
vagrant/devmode/salt/roots/build_deps.sls
vagrant/devmode/salt/roots/top.sls

I know this one is going to make travicCI unhappy.

Wip restore auth

---

tests/calamari_ctl.py
tests/http_client.py
tests/test.conf.template

add SSL support for the integration tests

---

calamari-common/calamari_common/remote/mon_remote.py

fix epoch of fsmap(mdsmap) for jewel

---

calamari-web/calamari_web/views.py

redirect the api because we no longer server the dashboard

---

cthulhu/cthulhu/calamari_ctl.py

fix failing os.path.exists

---

cthulhu/cthulhu/manager/pool_request_factory.py

fix when size and min_size are not in the request

---

cthulhu/cthulhu/manager/crush_node_request_factory.py

stop removing osds twice

---

rest-api/calamari_rest/urls/v2.py

remove urls for logs, keys, grains

---

rest-api/calamari_rest/views/v1.py

remove salt grains from info endpoint

---

cthulhu/cthulhu/manager/cluster_monitor.py
cthulhu/cthulhu/manager/server_monitor.py
cthulhu/tests/test_server_monitor.py

fix mon_list for mons built from monmap

---

cthulhu/cthulhu/manager/server_monitor.py

fix on_mon_map when mon_status object in None

---

cthulhu/cthulhu/manager/eventer.py

fix mangling of leader_name

---

cthulhu/cthulhu/manager/server_monitor.py

fix fqdn for OSDs where osd_metadata gives us hostname

---

cthulhu/cthulhu/manager/server_monitor.py
cthulhu/tests/test_server_monitor.py
tests/test_crush.py

fix case where down and out OSDs do not report metadata

---

salt/srv/salt/_modules/rbd_api.py

calamari:add the python rbd api for calamari
Signed-off-by: song baisen song.baisen@zte.com.cn

calamari:add the python rbd api for calamari

---

calamari-common/calamari_common/remote/mon_remote.py

calamari_common: Implement MonRemote.get_running

---

cthulhu/cthulhu/manager/server_monitor.py

These patches should help with issues we have been having with the osd discovery in calamari.

Fix osd discovery

---

rest-api/calamari_rest/views/v1.py

info: Do not mismatch fqdn/hostname

---

cthulhu/cthulhu/calamari_ctl.py

This sets the limit to half the available memory or does not set it at
all if it fails to parse the /proc/meminfo file.
I have tested this on RHEL and it was able to limit the memory to half the available memory.

memory: Limit progressively based on available memory

---

calamari-common/calamari_common/config.py
calamari-lite/calamari_lite/server.py
conf/calamari/debian/calamari.conf
conf/calamari/el6/calamari.conf
conf/calamari/rhel7/calamari.conf
conf/calamari/suse/calamari.conf
dev/calamari.conf.template
doc/calamari.conf

web: Introduce force_tls option

---

vagrant/centos7-build/Vagrantfile

the old value for "config.vm.box" is unavailable, please update this value ""centos/7""

update the config.vm.box

---

conf/calamari/debian/calamari.conf
conf/calamari/el6/calamari.conf
conf/calamari/rhel7/calamari.conf
conf/calamari/suse/calamari.conf
cthulhu/cthulhu/manager/eventer.py
cthulhu/cthulhu/manager/manager.py

This patchset contains a couple of fixes for the issues I noticed while testing salt-less deployment of calamari.

Various fixes to avoid salt
