cthulhu/cthulhu/manager/eventer.py
cthulhu/tests/test_eventer.py

@dmick @jcsp
We are looking for differences in osd_maps old vs. new and by mistake
the old version was compared to itself to determine if osds were added
or removed so there would never be events for those
Adds tests
Fixes: #10444

cthulhu: stop comparing osd data from the previous map in _on_osd_map

---

calamari-common/calamari_common/types.py

@dmick 
This info gets sent across in a messagepack and hence needs to be
able to be serialized which a defaultdict cannot.
Fixes: #10446

cthulhu: fix parent_bucket_by_node_id return to be serializable

---

rest-api/calamari_rest/serializers/v2.py

This allows zerorpc to understand how to convert our data to a
messagepack
@dmick

rest-api: coerce nested serializers to simple data types

---

vagrant/centos-build/Vagrantfile
vagrant/centos-build/salt/roots/build_deps.sls
vagrant/centos-build/salt/roots/git_clone.sls
vagrant/centos-build/salt/roots/make_packages.sls
vagrant/centos-build/salt/roots/setvars
vagrant/precise-build/Vagrantfile
vagrant/precise-build/salt/roots/build_deps.sls
vagrant/precise-build/salt/roots/git_clone.sls
vagrant/precise-build/salt/roots/make_packages.sls
vagrant/precise-build/salt/roots/setvars
vagrant/rhel-build/Vagrantfile
vagrant/rhel-build/salt/roots/build_deps.sls
vagrant/rhel-build/salt/roots/git_clone.sls
vagrant/rhel-build/salt/roots/make_packages.sls
vagrant/rhel-build/salt/roots/setvars
vagrant/rhel7-build/Vagrantfile
vagrant/rhel7-build/salt/roots/build_deps.sls
vagrant/rhel7-build/salt/roots/git_clone.sls
vagrant/rhel7-build/salt/roots/make_packages.sls
vagrant/rhel7-build/salt/roots/setvars
vagrant/trusty-build/salt/roots/build_deps.sls
vagrant/trusty-build/salt/roots/git_clone.sls
vagrant/trusty-build/salt/roots/make_packages.sls
vagrant/trusty-build/salt/roots/setvars
vagrant/wheezy-build/Vagrantfile
vagrant/wheezy-build/salt/roots/build_deps.sls
vagrant/wheezy-build/salt/roots/git_clone.sls
vagrant/wheezy-build/salt/roots/make_packages.sls
vagrant/wheezy-build/salt/roots/setvars

Allow the salt structure to be used with or without Vagrant.  Also, make all vagrant VMs 1024k (some were 
consistently running out of memory).

Parameterize salt

---

calamari.spec

This pull request updates the RPM Summary and %description to remove references to Inktank.

calamari.spec: remove Inktank reference

---

get-flavor.sh

Do not look for specific strings in VERSION field, just use the shell
built-in pattern matching mechanism.

Handle VERSION in a more future-proof way

---

calamari.spec

Prior to this pull request, during the RPM installation, a message would be printed to STDOUT that tells the user to run calamari-ctl using sudo.
Not all Red Hat systems are set up for sudo. Update the message to use the more general instruction "run X as root" instead.
This change comes from Boris Ranto @branto1 , from the downstream Red Hat Ceph Storage packages.

calamari.spec: avoid sudo in RPM %post instructions

---

calamari.spec

RPM permits us to combine the `%dir` and `%attr` RPM macros on the same lines in the `%files` lists. This allows us to reduce duplication in the `%files` list by only specifying the `/var/log` locations once instead of specifying them twice.
This change comes from @branto1 , from the downstream Red Hat Ceph Storage packages.

calamari.spec: simplify log files lists

---

salt/srv/salt/diamond.sls

@dmick @ktdreyer @jcsp 
caused diamond to fail to install on rhel7

salt: remove old workaround for systemd

---

Makefile

@dmick  This stops travisCI from failing builds based on the new flake8 whining

Silence foul flake8

---

calamari.spec

The file attributes were previously set in %post script by chown command. This causes tools like rpm -V to fail. This patch modifies this behaviour to use the proper %attr macros in %files list in order to fix this.

Set file attributes with %attr, not chown

---

calamari-common/calamari_common/salt_wrapper.py

Replace salt.loader.static_loader from newer
salt versions with _create_loader, which is
compatible with older salt versions.
Signed-off-by: Alex Muntada <alexm@alexm.org>

cthulhu: make it work with salt 2015.5.0

---

calamari-common/calamari_common/types.py
cthulhu/cthulhu/manager/server_monitor.py

There's a slightly bizarre edge case, where if you have an OSD in DNE
state (i.e. it's in the CRUSH map, but doesn't actually exist), this
causes various errors (IndexError, NotFound etc.) due to the osd_map
being out of sync with both the crush map and service state.  For
initial discussion of this problem, see:
http://lists.ceph.com/pipermail/ceph-calamari-ceph.com/2015-May/000092.html
This fix injects a fake OSD at the lowest level possible, which means
it appears everywhere it should, and can be displayed in a suitably
scary red color.
Note that the injected fake OSD may not have the best values for its
attributes -- most/all of them seem to need to exist, but perhaps should
default to "unknown" or empty strings rather than my excessive use of
"DNE".
Signed-off-by: Tim Serong …

Handle OSDs that do not exist

---

Makefile
calamari.spec
selinux/calamari-server.te

This patch adds a custom initial SELinux policy for calamari to the upstream package. This is essential to get calamari to function with SELinux in Enforcing mode.
btw: This patch also adds few more build-time dependencies that are necessary to build calamari by mock.

Add initial SELinux policy for calamari-server

---

tests/test_permissions.py

Change to use the api_username in tests/test.conf as user name. It can fix the test permissions failed at user name admin is not existed.

Fix the test failed happened at user 'admin' is not exists

---

calamari-common/calamari_common/types.py

Submitted fix for #311, let me know what you think.

types.py: Fixup missing crush_node_by_id initialization when data is set to None

---

cthulhu/cthulhu/calamari_ctl.py

@tserong Thank you! 
Noticed this from the mailing list and it works for me.
This fixes two problems:
1) Popen(["salt"], "'*'", "state.highstate"]) passes '*' i.e. a single
quoted star to salt, which doesn't work - it needs to be a bare star,
else it can't match hostnames, and returns rc=2 causing calamari-ctl
initialize to report a failure ("No minions matched the target. No
command was sent, no jid was assigned").
2) salt * state.highstate fails with the same error on the first run, if
there are no connected minions.
Signed-off-by: Tim Serong <tserong@suse.com>
(cherry picked from commit f54cf4259c5b6629269118b4b909f6418a69dc40)

calamari-ctl: Fix "No minions matched the target" when updating minions

---

cthulhu/tests/test_server_monitor.py

Signed-off-by: Tim Serong <tserong@suse.com>

tests: Allow CALAMARI_CONFIG override in test_server_monitor

---

vagrant/devmode/Vagrantfile
vagrant/devmode/salt/roots/build_deps.sls

salt-bootstrap is broken on precise, this is the easiest transition
to get it working

devmode: move to trusty from precise

---

tests/calamari_ctl.py

@dmick I thought we relaxed the requirement for info.yaml already
For some reason this fails to rebase cleanly to 1.2.3 hence the DNM

Wip fix devmode

---

cthulhu/cthulhu/manager/cluster_monitor.py
cthulhu/cthulhu/manager/request_collection.py

cluster_monitor watches a specific cluster FSID
request_collection is a collection of all requests in all clusters
This fix changes the filter that request_collection uses when fail_all()
is called.
Fixes: #13173

cthulhu: Fail correct UserRequests when choosing a new favorite mon

---

rest-api/calamari_rest/urls/v2.py

rest-api: fix typo in url routing for osd/command

---

calamari.spec

@ktdreyer @dmick 
The problem is that the rest-api errors out with an IOError: permission
denied as it imports the salt_wrapper and the wrapper tries to intialize
a logHandler for cthulhu.log
This wrapper wants to log import
failures to both calamari.log and cthulhu.log. Because it doesn't know
who is using it. A better fix might be to pass in a logHandler
Without this patch
cthulhu.log will be owned by root as cthulhu runs as root.
The fix is to chown all the log files in /var/log/calamari to the apache
user.

add %dir directive

---

conf/calamari/debian/calamari.conf
conf/calamari/el6/calamari.conf
conf/calamari/rhel7/calamari.conf
conf/calamari/suse/calamari.conf
cthulhu/cthulhu/manager/eventer.py
dev/calamari.conf.template
doc/calamari.conf

This patch adds an option to push events generated by
calamari to salt event bus. This can be enabled by
setting the option emit_event_to_salt_event_bus to True,
by default this will be set to false. Also there is an
option to set the prefix of the tag of the event pushed.
This can be done using the option "event_tag_prefix". By
default its value is "calamari/". These options are
available in calamari.conf file under [cthulhu].
Signed-off-by: Darshan N <dnarayan@redhat.com>

Cthulhu: Optionally push events to salt event bus

---

salt/srv/salt/diamond.sls

grains['os'] == 'RedHat' really just works out for RHEL but not for centos and co.
whereas grains['os_family'] == 'RedHat' also works for the later

fix so that it also works with centos and the like

---

doc/calamari_rest/conventions.rst

Corrected the variable name specified in the description to that specified in the example.

Corrected the page size variable from page count.

---

calamari-common/calamari_common/salt_wrapper.py
conf/supervisord.production.conf

This module gets imported by cthulhu calamari_ctl and rest_api
The permissions on the log files are inherited from the process
previously we just tried to log to all the files which got us in
troublein the case where rest_api(uid: apache) tries to open
cthulhu.log(owner:root)
Fix this at the correct level of abstraction import errors
get sent to stderr use supervisor to catch them on cthulhu
apache should be getting them for rest-api and they all end
up as /var/log/calamari/*.log

calamari-common: log salt import failures with supervisor

---

Makefile
calamari-lite/calamari_lite/server.py
calamari-web/calamari_web/settings.py
calamari.suse.spec
conf/calamari.service
conf/calamari/suse/calamari.conf

This is about the minimum amount necessary to create an RPM package for Calamari-on-MON which uses distro packaged dependencies (python-django etc.) rather than packing everything into a virtualenv. It also adds a systemd unit file for calamari lite, so we don't need supervisord. I've done the spec file as a SUSE-specific variant to make it easy to see what it looks like, rather than editing the existing calamari.spec. Comments appreciated ;-)

RFC: Add LSB build targets, systemd unit file, SUSE spec

---

calamari-common/calamari_common/remote/mon_remote.py

problem: cluster_name argument was getting
passed another instance of ClusterHandle
TODO: add tests
Resolves: BZ1322905

mon_remote: fix ClusterHandle instantiation

---

salt/srv/salt/_modules/ceph.py

This is derived from commit 5c331c2 on the 1.4 branch (except that's on
mon_remote.py), but will try to get the fsmap epoch if present instead
of the mdsmap epoch.
Rationale: The Jewel release `ceph status` JSON blob includes an
"fsmap" dict, apparently instead of the old "mdsmap" dict.  This means
that the current implementation of the salt module will fail with
"KeyError: 'mdsmap'" when run against Jewel.  AFAICT this exception
isn't actually reported anywhere, it just silently fails and Calamari
thinks there's no cluster configured.
Signed-off-by: Tim Serong <tserong@suse.com>

ceph-module: handle fsmap epoch to support Jewel

---

Makefile
requirements/2.7/requirements.production.txt

Prior to Carbon 0.9.11, Carbon's `setup.py` script would install files to `/etc/init.d`. To avoid this behavior, Calamari's `Makefile` used `sed` to rewrite `setup.py` and stop doing that.
Newer versions of Carbon have dropped this mis-feature, so we can now rely on the stock version from PyPI without the hack.
Drop the custom `Makefile` bits that rewrote carbon's `setup.py` script. Add carbon to the production requirements.txt. (0.9.15 is the latest upstream version at the time of this commit.)
Thanks @dmick for helping with investigating this issue.
This change has the side effect of giving us compatibility with Ubuntu Xenial's pip v8.1.1. Pip 8 has no longer supports the `--no-install` and `--no-download` arguments to `pip install`.

drop carbon setup.py hack and use carbon 0.9.15

---

debian/control

On Ubuntu Xenial, the package is "virtualenv".

debian/control: try installing virtualenv first, if it exists

---

Makefile
requirements/2.7/requirements.production.txt

My previous patch (https://github.com/ceph/calamari/commit/55fb7c683ca29d87b9f337960d8f9bac8bb481c4) went too far in simplifying the carbon installation, because carbon 0.9.x still tries to write to `/opt/graphite`.
Re-do the change, keeping the `build-venv-carbon` make target, and just removing the `--no-install` + `sed` + `--no-download` bits.

simplify carbon install, take 2

---

debian/control

remove salt depends in calamari-server on ubuntu

---

salt/local/postgres.sls

`initdb` creates contents in `data/*` including a `pg_hba.conf`. When installing postgresql this directory is empty.
On an upgrade situation, that directory wouldn't be empty and the command would fail.
RH BZ issue: https://bugzilla.redhat.com/show_bug.cgi?id=1333210

only run initdb when pg_hba.conf hasn't been created. Fixes rhbz 1333210

---

cthulhu/cthulhu/calamari_ctl.py

When calamari-ctl intiialize gets invoked
via salt it failed with "Data failed to compile:"
so we now set concurrent=True we don't expect
to be changing any state that would cause problems

fix salt-call invocation from salt-call

---

cthulhu/cthulhu/manager/server_monitor.py

We no longer have to infer the names of OSD hosts
from the crushmap.

get hostnames for server endpoint from osd_metadata

---

salt/srv/salt/base/calamari-crush-location.py

If the last CRUSH location isn't set for an OSD (which apparently it
usually won't be), calamari-crush-location prints out error messages
which eventually appear in `systemctl status ceph-osd@$N` output:
ERROR:calamari_osd_location:Error 2 running ceph config-key get:'Error
ENOENT: error obtaining
'daemon-private/osd.2/v1/calamari/osd_crush_location': (2) No such file
or directory'
This makes it look like something is broken, when everything is actually
fine, so this commit suppresses ENOENT errors.
Signed-off-by: Tim Serong <tserong@suse.com>

calamari: ignore ENOENT in calamari-crush-location

---

conf/calamari/debian/calamari.conf
conf/calamari/el6/calamari.conf
conf/calamari/rhel7/calamari.conf
conf/calamari/suse/calamari.conf

There is code that tries to chown some paths
to be RW by apache, since we're no longer
using apache to server and aren't depending on
the httpd package there is not user to
successfully chown this stuff to
calamari-lite runs as root leave them root

fix calamari-ctl initialize

---

vagrant/trusty-build/salt/roots/git_clone.sls

We fail if the current repo is newer than what is currently in the git repos. This will allow salt to update the refs.

vagrant/trusty-build: force reset the git repos

---

salt/srv/salt/_modules/ceph.py

The command can return non-zero value if the osds are not fully ready,
yet. Ignore this and create a structure containing only the osd id to
avoid getting internal server error (http error 500).

Do not assert 0 for osd metadata command

---

calamari-server.spec.in

We can later use jenkins to generate a regular spec file from the template as in
https://github.com/ceph/ceph-build/blob/master/calamari-setup/build/build#L43

rpm: Make spec file a template

---

salt/srv/salt/diamond.sls

the version of diamond that we currently lacks
systemd control files. I've rebased our work on
diamond-4.0 which will fix this correctly so that
we can use systemd to start it. This initscript
workaround is here till that package gets tested
and accepted upstream.

diamond: start the service with the initscript

---

selinux/calamari-server.te

Will not build on fedora 24 because module name does not match package name
/usr/bin/checkmodule:  Module name calamari is different than the output base filename calamari-server

Updated the module name to match the package name

---

calamari-common/calamari_common/remote/mon_remote.py
salt/srv/salt/_modules/ceph.py

Currently, we run these commands with default stdin which resolves to
tty from which the daemon is run. For commands like 'rbd watch <img>'
which wait for an input, this can result in commands being hung forever.
The patch fixes it by attaching the stdin to /dev/null so the commands
like that will get EOF on stdin and exit immediately.

Pass /dev/null as stdin when calling ceph commands

---

calamari-common/calamari_common/remote/mon_remote.py
rest-api/calamari_rest/serializers/v2.py
rest-api/calamari_rest/urls/v2.py
rest-api/calamari_rest/views/v2.py

The commit adds two stats endpoints that provide global cluster as well
per pool statistics.

Add /cluster/<fsid>/{pool/<id>/}stats endpoints

---

requirements/2.7/requirements.production.txt

In the Calamari 1.4 series, we had `gevent>=1.1` in `requirements.txt`.
Commit 14bf202abdeb9c4b0d2cabe365f483eb4eb7a054 altered the gevent version slightly to pin to an exact gevent version (v1.1.0).
This means we went slightly backwards from Calamari v1.4.z, because `>=1.1` would cause Pip to pull in gevent v1.1.1, whereas now we pin to v1.1.0.
After discussing with gmeno, let's continue using gevent 1.1.1 here.

bump gevent to 1.1.1 for Calamari 1.5

---

debian/control

When dh_python2 parses the `requires.txt` files in Calamari and Calamari's bundled libraries, it translates the dependencies listed there into "python-" packages and adds them into `${python:Depends}`.
In the past this has led to the calamari-server .deb depending on system packages that do not exist, which leads to installation failures.
Since `${python:Depends}` doesn't work well with Calamari's method of bundling libraries in a virtualenv, just remove it and hard-code the list of python Depends in /debian/control.
(I've just copied & pasted the existing list that dh_python2 was already picking up, so maybe this Depends list could be trimmed further, with experimentation.)

debian: stop using dh_python2 ${python:Depends}

---

requirements/lite.txt

In commit 7075d889f50bc3e33ae5f680a0aad605dc8e4917, I bumped gevent to 1.1.1. Bump lite.txt as well to match this.

lite.txt: bump gevent to 1.1.1

---

calamari-server.spec.in
debian/calamari-server.postinst

Now that we run as root and serve HTTPS without Apache, we don't need to chown directories to the apache user. In fact, since the RPM and Deb doesn't depend on the Apache packages any more, this UID may not even exist on the system.
For RPMs, this could lead to UID/GID warnings in `rpm --verify calamari-server`, since the rpmdb thinks directories should be owned by "apache", but they end up owned by "root" when the httpd RPM is not installed.

packaging: drop "apache" uid/gid ownership on directories

---

vagrant/centos7-build/Vagrantfile

boxcutter/centos71 is no longer available from https://atlas.hashicorp.com/boxcutter/centos71

Bump Centos 7 vm box version to centos73

---

cthulhu/cthulhu/manager/server_monitor.py

The cluster or backend address do not need to be resolvable. We can't
use it to get the host name/fqdn reliably. We need to use public (front)
address which has to be resolvable.

server_monitor: Use public/front_addr to resolve names

---

build-rpm.sh

Adapted from [here](https://github.com/ceph/ceph-build/blob/master/calamari/build/build_rpm).

Fix build-rpm.sh spec
